### PR TITLE
added indexed functions to current & added getOrigins function

### PR DESCRIPTION
**Pull request by RedSparr0w**
added index to stickers

### CODE REVIEW

**Comment by Ballrock** [comment]
Sorry for late answer. A new version will be release soon (this week if all goes well) which includes among these evolutions : ID for all objects (including for exemple weapons, collections and stickers).
Despite of this, I do not envisage, for now, to modify the arrays to add fixed index for the objects  

I really thank you for this PR :+1:. In order to find the best solution to your problem can you describe a bit more your needs about stickers ?

**Comment by Ballrock** [comment]
0.1.0 is out.
I close this PR, you are free to open an issue/PR about index handling in this version :smile:

**Comment by RedSparr0w** [comment]
main reason for wanting the fixed indexes is because of the way steam generally returns item information via api/proto.
for example getting item information via inspect link returns this

```
{  
   "iteminfo":{  
      "accountid":null,
      "itemid":{  
         "low":405091507,
         "high":1,
         "unsigned":true
      },
      "defindex":7,
      "paintindex":282,
      "rarity":5,
      "quality":4,
      "paintwear":"0.17915000021457672",
      "paintseed":288,
      "killeaterscoretype":null,
      "killeatervalue":null,
      "customname":null,
      "stickers":[  
         {  
            "slot":0,
            "sticker_id":938,
            "wear":null,
            "scale":null,
            "rotation":null
         },
         {  
            "slot":1,
            "sticker_id":938,
            "wear":null,
            "scale":null,
            "rotation":null
         },
         {  
            "slot":2,
            "sticker_id":938,
            "wear":null,
            "scale":null,
            "rotation":null
         },
         {  
            "slot":3,
            "sticker_id":938,
            "wear":null,
            "scale":null,
            "rotation":null
         }
      ],
      "inventory":12,
      "origin":8,
      "questid":null,
      "dropreason":null
   }
}
```

Maybe it could be a seperate function?

```
infos.baseWeapons = csgoDataParser.getWeaponsIndexed();
```

or built into the current ones?

```
infos.baseWeapons = csgoDataParser.getWeapons(true); // Fixed Index
infos.baseWeapons = csgoDataParser.getWeapons(false); // No Fixed Index
infos.baseWeapons = csgoDataParser.getWeapons(); // No Fixed Index
```

**Comment by Ballrock** [comment]
On reflection, I think you have a good point about this.

In my mind `infos.baseWeapons = csgoDataParser.getWeaponsIndexed();` is preferable 
 for easy understanding of the method usage.

Beside, i need to focus on refactoring code and create unique result methods which are reusable... like :
`var deagle = csgoDataParser.getWeapon(indexDeagle);`

Feel free to edit your PR :)

Really thank you for your time and your advices :+1: Have a nice day

**Comment by RedSparr0w** [comment]
Only problem i can see with `infos.baseWeapons = csgoDataParser.getWeaponsIndexed();` is the fact that this will add a lot of unnecessary lines to the code.
+1492 chars | +26 lines Difference (on `getStickers();`)

## infos.baseWeapons = csgoDataParser.getStickersIndexed();

### 3291 chars | 75 lines

```
    getStickers() {
        /*jshint eqeqeq: false, eqnull:true, camelcase: false */
        var self = this;
        var timer = misc.generateTimer();
        self.logger.info('');
        self.logger.info('');
        self.logger.info('-----------------------------------------');
        self.logger.info('------- Stickers List Generation --------');
        self.logger.info('-----------------------------------------');
        self.logger.info('');

        var stickers=[];
        var rawstickers = this.itemsData.items_game.sticker_kits;

        Object.keys(rawstickers).forEach(function(key){
            //Remove the default Sticker by remove 0 key
            if (key !== '0') {
                var timerStickers = misc.generateTimer();
                var sticker=new Sticker();
                sticker.name=self.getLangValue(rawstickers[key].item_name);
                sticker.techName=rawstickers[key].name;
                sticker.defIndex=key;
                if (rawstickers[key].item_rarity == null) {
                    sticker.rarity='default';
                } else {
                    sticker.rarity=rawstickers[key].item_rarity;
                }
                stickers.pushUniqueNamedObject(sticker);
                self.logger.info('Fetch ' + sticker.name + ' sticker [' + misc.resultTimer(timerStickers) +'s]');
            }
        });

        var totalStickers=stickers.length;
        self.logger.info('-----------------------------------------');
        self.logger.info('Generate ' + totalStickers + ' stickers [' + misc.resultTimer(timer) +'s]');
        return stickers;
    }
    getStickersIndexed() {
        /*jshint eqeqeq: false, eqnull:true, camelcase: false */
        var self = this;
        var timer = misc.generateTimer();
        self.logger.info('');
        self.logger.info('');
        self.logger.info('-----------------------------------------');
        self.logger.info('------- Stickers List Generation --------');
        self.logger.info('-----------------------------------------');
        self.logger.info('');

        var stickers={};
        var rawstickers = this.itemsData.items_game.sticker_kits;

        Object.keys(rawstickers).forEach(function(key){
            //Remove the default Sticker by remove 0 key
            if (key !== '0') {
                var timerStickers = misc.generateTimer();

                if (rawstickers[key].item_rarity == null) {
                    var rarity='default';
                } else {
                    var rarity=rawstickers[key].item_rarity;
                }
                stickers[key] = {
                    'name':self.getLangValue(rawstickers[key].item_name),
                    'techName':rawstickers[key].name,
                    'item_rarity':rarity
                    };
                self.logger.info('Fetch ' + stickers[key].name + ' sticker [' + misc.resultTimer(timerStickers) +'s]');
            }
        });

        var totalStickers=Object.keys(stickers).length;
        self.logger.info('-----------------------------------------');
        self.logger.info('Generate ' + totalStickers + ' stickers [' + misc.resultTimer(timer) +'s]');
        return stickers;
    }
```

# -VS-

## infos.baseWeapons = csgoDataParser.getStickers(true);

### 1799 chars | 49 lines

```
    getStickers(indexed) {
        /*jshint eqeqeq: false, eqnull:true, camelcase: false */
        var self = this;
        var timer = misc.generateTimer();
        self.logger.info('');
        self.logger.info('');
        self.logger.info('-----------------------------------------');
        self.logger.info('------- Stickers List Generation --------');
        self.logger.info('-----------------------------------------');
        self.logger.info('');
        var stickers;
        var rawstickers = this.itemsData.items_game.sticker_kits;
        (indexed ? stickers={} : stickers=[]);
        Object.keys(rawstickers).forEach(function(key){
            //Remove the default Sticker by remove 0 key
            if (key !== '0') {
                var timerStickers = misc.generateTimer();
                if (indexed){
                    if (rawstickers[key].item_rarity == null) {
                        var rarity='default';
                    } else {
                        var rarity=rawstickers[key].item_rarity;
                    }
                    stickers[key] = {
                        'name':self.getLangValue(rawstickers[key].item_name),
                        'techName':rawstickers[key].name,
                        'item_rarity':rarity
                    };  
                }else{
                    var sticker=new Sticker();
                    sticker.name=self.getLangValue(rawstickers[key].item_name);
                    sticker.techName=rawstickers[key].name;
                    sticker.defIndex=key;
                    if (rawstickers[key].item_rarity == null) {
                        sticker.rarity='default';
                    } else {
                        sticker.rarity=rawstickers[key].item_rarity;
                    }
                    stickers.pushUniqueNamedObject(sticker);
                }
                self.logger.info('Fetch ' + rawstickers[key].name + ' sticker [' + misc.resultTimer(timerStickers) +'s]');
            }
        });

        var totalStickers=Object.keys(stickers).length;
        self.logger.info('-----------------------------------------');
        self.logger.info('Generate ' + totalStickers + ' stickers [' + misc.resultTimer(timer) +'s]');
        return stickers;
    }
```

edit: also by using the param in 2nd example only people who need the indexed option may get confused (hopefully not) as without any param `getStickers();` will return data how it does now

**Comment by Ballrock** [comment]
An alternative for avoid code duplication but keep `getWeaponsIndexed()` can be of use it only as an alias.

Like : 
- Default :  getWeapons() (Not Indexed)
- Indexed : getWeaponsIndexed() -> call getWeapons(true)
- Not Indexed : getWeapons() or getWeapons(false)

**Comment by RedSparr0w** [comment]
Yeah, makes sense, sounds like the better idea

**Comment by RedSparr0w** [comment]
Updated the branch to latest, 

Merged with changed files.

**Comment by RedSparr0w** [comment]
Didn't add indexed option to exteriors/wear as index not referenced
anywhere.

Changed `getRaritiesIndex` to `getRarities` as to avoid confusion when
`getRaritiesIndexed` is implemented

TO DO
- [x] Create Alias
- [x] Add `getOrigins`
- [ ] Add `getQualities`

**Comment by Ballrock** [comment]
Nice ! I will take a look this evening :smile:

**Comment by Ballrock** [comment]
I'm really sorry for the delay, i forgot a bit this repo and I was really busy with my new job ^^'

I'm checking these commit and.. this is really a good work !

For the moment the only little things i can object about are : 
- the JSDocs, the new parameters aren't in.
- I'm not a big fan of ternary expressions but, in this context, why not :smile: 
- In my opinion getXIndexed() are just alias and can be regroup.
- These alias also not have JSDocs.
- I think JUnit of indexed alias can be regroup with main fonction group

I will check a bit about performance later.

If you dont have time for that or if you think i'm fussy (which i really am). I can merge this and do the rest on my side ;)

Anyways, I thanks you a lot for your great work :clap:

**Comment by RedSparr0w** [comment]
Forgot about this XD,

Thanks for the merge, might pay to update the game files used too [=

**Pull request merged**
